### PR TITLE
Enable /people/add method

### PR DESCRIPTION
**Pull request by kaip**
@nationbuilder/internal-collaborators Adds new /people/add endpoint (used for regulator)

### CODE REVIEW

**Comment by DavidHuie** [comment]
The correct workflow for this is to first update the API Explorer (steps are in the readme): https://github.com/3dna/api_explorer

Once you've updated it, you can just copy over the JSON file it generates to overwrite the one in this project. I think we might have this documented, but I don't have the wiki page on hand. Sorry!

**Comment by kaip** [comment]
Okay, using copied json file now

**Comment by DavidHuie** [comment]
:+1:

**Comment by correlator** [comment]
rad

**Pull request merged**
