### PR TITLE
Fix header Content-Type check

### PR DESCRIPTION
**Pull request by codealchemy**
Incorporates fix from #33 along with updating fixtures.

@nationbuilder/internal-collaborators cc: @bxjx

### CODE REVIEW

**Comment by kaip** [comment]
How do we write a test for this change?

**Comment by codealchemy** [comment]
@kaip the updated fixtures covered it - a fresh pull had 8 failures without the change, all on 

```ruby
NoMethodError: undefined method `[]' for true:TrueClass
```

**Comment by darinwilson** [comment]
Thanks for the quick fix, folks! Will you be pushing out a new gem version for this fix, or should we just point our Gemfiles directly at this repo for now?

**Comment by codealchemy** [comment]
@darinwilson working on a release soon (some other changes since the last release complicated things a bit) , in the meantime you can point to the change here in your Gemfile to get the latest updates.

**Pull request merged**
